
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkokfyhpdxvuuzigpmiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrb2tmeWhwZHh2dXV6aWdwbWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTYxMzEsImV4cCI6MjA2MDU3MjEzMX0.U_he-R04oDskQkbCBO8LpBYsEf4yhGOgtqKU6zdGivM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
